name: test

on:
  workflow_dispatch:
  schedule:
    - cron: "35,50 23 * * 0-4"
    - cron: "5 0 * * 1-5"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests
      - run: python test_nxt.py
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT: ${{ secrets.TG_CHAT }}
